apiVersion: v1
kind: Service
metadata:
  name: meu-servico-node-mult
spec:
  type: NodePort
  selector:
    run: nginx
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080 #Se nao setar, gera automatico
    name: http
  - port: 44443
    targetPort: 443
    nodePort: 30443
    name: https