---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit
spec:
  limits:
  # - default:
  #     memory: 512Mi
  #   defaultRequest:
  #     memory: 256Mi
  - max:
      cpu: "500m"
    min:
      cpu: "200m"
    type: Container