apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leitor-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leitor-cluster
subjects:
  - kind: ServiceAccount #User, ServiceAccount, Group
    name: leitor-global