apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leitor-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leitor-secrets
subjects:
  - kind: ServiceAccount #User, ServiceAccount, Group
    name: leitor
    namespace: default