apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: empty
  - image: busybox
    name: html-editor
    volumeMounts:
      - mountPath: /html
        name: empty
    command: ["/bin/sh", "-c"]
    args:
    - while true; do
        date >> /html/index.html;
        sleep 1;
      done
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: empty
    emptyDir: {}