apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primeiro-pvc
  namespace: day1
spec:
  storageClassName: "primeiro"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi