apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meu-rs
spec:
  selector:
    matchLabels:
      tier: web
  replicas: 3
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: tier
              value: "web"