apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
      - mountPath: /data
        name: secret-volume
    # env:
    #   - name: MEU_USER
    #     valueFrom:
    #       secretKeyRef:
    #         key: user
    #         name: minha-secret
    # envFrom:
    #   - secretRef:
    #       name: minha-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: secret-volume
      secret:
        secretName: minha-secret
        # items:
        # - key: user
        #   path: meu_usuario.config